### ISSUE TITLE
@archanova/cli on all commands: TypeError: Cannot read property 'getConfig' of undefined 

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#36]
## Description

When using any command [In the CLI documentation](https://github.com/netgum/archanova/blob/develop/packages/cli/README.md), the console will read that there is a console error

**Comment by lyricalpolymath** [comment]
same here... can it be due to the node version?

```
MacBook-Pro:Abridged_test01 b$ archanova-cli
/Users/b/.nvm/versions/node/v8.9.0/lib/node_modules/@archanova/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read property 'getConfig' of undefined
    at Object.<anonymous> (/Users/b/.nvm/versions/node/v8.9.0/lib/node_modules/@archanova/cli/build/bin.js:31:36)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

command achanova-cli -help
```
MacBook-Pro:Abridged_test01 b$ archanova-cli -help
/Users/b/.nvm/versions/node/v8.9.0/lib/node_modules/@archanova/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Unsupported env
    at Object.getCliConfig (/Users/b/.nvm/versions/node/v8.9.0/lib/node_modules/@archanova/cli/build/cli.js:66:15)
    at Object.<anonymous> (/Users/b/.nvm/versions/node/v8.9.0/lib/node_modules/@archanova/cli/build/bin.js:15:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
MacBook-Pro:Abridged_test01 b$ 
```

**Comment by stanislaw-glogowski** [comment]
Fixed
