### ISSUE TITLE
Uncaught exception | 502 Bad Gateway error | Sokol

### ISSUE THREAD

**Issue by RyRy79261** [netgum/archanova#83]
## Description

When submitting transactions, the relayer returns a 502 cloudflare error intermittently 

```
{ Error: invalid response - 502
 |     at exports.XMLHttpRequest.request.onreadystatechange (C:\Users\ryan\Documents\repos\protea-gather-beta-v2\ApiServer\node_modules\ethers\utils\web.js:84:29)
 |     at exports.XMLHttpRequest.dispatchEvent (C:\Users\ryan\Documents\repos\protea-gather-beta-v2\ApiServer\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
 |     at setState (C:\Users\ryan\Documents\repos\protea-gather-beta-v2\ApiServer\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
 |     at IncomingMessage.<anonymous> (C:\Users\ryan\Documents\repos\protea-gather-beta-v2\ApiServer\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
 |     at IncomingMessage.emit (events.js:194:15)
 |     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
 |     at endReadableNT (_stream_readable.js:1125:12)
 |     at process._tickCallback (ApiServer\internal\process\next_tick.js:63:19)
 |   statusCode: 502,
 |   responseText:
 |    '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>\r\n' }
```

**Comment by RyRy79261** [comment]
Was rate limiting, closing
